Script started on 2017年03月15日 (週三) 17時22分36秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1-new $[00m g==[K[K++ lab[K[K[K-0la[K[K[Ko lab1-new [K-test lab1-new.cpp
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1-new $[00m ./lab1-new-test[K[K[K[K[K-test [K[K[K[K[K[K[K[K[K[K[K[K[K[Klab1-new-test 
請輸入一正整數
22
22
11
34
17
52
26
13
40
20
10
5
16
8
4
2
1
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1-new $[00m D[K
Script done on 2017年03月15日 (週三) 17時24分11秒
